*************************************************************************;
* Program name      : @@program_name
*
* Program path      : root/cdar/d693/d6935c00003/ar/dr1/tlf/dev/program
*
* Type              : SAS program
*
* Purpose           : @@purpose
*
* Author            : @@author
*
* Date created      : @@date
*
* Input datasets    : ADAM.ADXX
*
* Macros used       : %setup, %localsetup, %procprint_indi, %logcheck_indi, %istartv2, %istopv2, %m_u_popn, %m_u_report
*
* Output files      : @@output
*
* Usage notes       :  
**************************************************************************;
%setup(version=260,
	   localsetup=root/cdar/%scan(&_exec_programpath.,3,/)/%scan(&_exec_programpath.,4,/)/ar/%scan(&_exec_programpath.,6,/)/common/%scan(&_exec_programpath.,8,/)/macro/localsetup.sas);

%localsetup;

proc datasets lib=work kill nowarn nodetails nolist mt=data;
quit;

options mprint mlogic symbolgen;
dm "output; clear;";
dm "log; clear;";

%let PGMNAME=%scan(&_EXEC_PROGRAMNAME,1, ".");
%put &PGMNAME.;
%procprint_indi;

*---------------------------------------------------------------------------------*;
*-------------------------Step 01: Set up-----------------------------------------*;
*---------------------------------------------------------------------------------*;

%let sfx = a;

/* Please add column description according to your layout.*/

proc format;
	value trtfmt 
	1 = " "
	2 = " "

	;
run;

/* Generate column header macro variable and bign table (WORK.TBIGN) */

%m_u_popn(
        inds=adam.adsl
        ,pop_flag=
        ,trtgrpn=
        ,trtlev=
        ,trtfmtC=trtfmt
        ,gmacro=popgrp
        ,BigN=Y
        ,nformat=%str(n (%%))
        ,debug=N
         ); 

*---------------------------------------------------------------------------------*;
*-------------------------Step 02: Derive final dataset for table-----------------*;
*---------------------------------------------------------------------------------*;

*-----------------Main body of TLF data programming - Start-----------------*;









*-----------------Main body of TLF data programming - End-----------------*;

data final;
set _inds_;

*-----Please add label for 'COL' variables as column header.-----*;
*-----Macro variables generated by %m_u_popn could be used.-----*;

/* label */
/* COL1 = "" */
/* COL2 = "" */
/* ... */
/* ; */
run;

/*For page-by variable, please rename to COL0*/

data tlf.&PGMNAME.&sfx.;
length COL: $1000.;
	set final(keep=COL:);
	array temp _char_;
	do over temp;
		temp = strip(temp);
	end;
run;

*---------------------------------------------------------------------------------*;
*-------------------------Step 03: Report-----------------------------------------*;
*---------------------------------------------------------------------------------*;

%istartv2(suffix=&sfx.);
 
%m_u_report(table=final);
 
%istopv2(debug=N);

*---------------------------------------------------------------------------------*;
*-------------------------Step 04: Log Check--------------------------------------*;
*---------------------------------------------------------------------------------*;

%logcheck_indi;


