"""PPTX Renderer for Platinum slide decks.

Creates PowerPoint presentations from SlideContent generated by PlatinumAgent.
"""

import logging
from pathlib import Path
from typing import List, Optional

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Pt

from olympus.platinum.agent import SlideContent, SlideDeck
from olympus.platinum.charts import add_chart_to_slide
from olympus.platinum.templates import (
    DEFAULT_LAYOUT,
    DEFAULT_TABLE_STYLE,
    DEFAULT_TEXT_STYLE,
)

logger = logging.getLogger(__name__)


class PPTXRenderer:
    """Renders slide content to PowerPoint format."""

    def __init__(
        self,
        layout: Optional[object] = None,
        text_style: Optional[object] = None,
        table_style: Optional[object] = None,
    ):
        self.layout = layout or DEFAULT_LAYOUT
        self.text_style = text_style or DEFAULT_TEXT_STYLE
        self.table_style = table_style or DEFAULT_TABLE_STYLE
        self.prs = None

    def create_presentation(self) -> Presentation:
        """Create a new presentation with default settings."""
        self.prs = Presentation()
        self.prs.slide_width = self.layout.width
        self.prs.slide_height = self.layout.height
        return self.prs

    def _get_slide_layout(self, slide_type: str):
        """Get appropriate slide layout for type."""
        if not self.prs:
            raise ValueError(
                "Presentation not created. Call create_presentation() first."
            )

        layout_idx = 5 if slide_type == "title" else 1
        return self.prs.slide_layouts[layout_idx]

    def _rgb_to_color(self, rgb: tuple) -> RGBColor:
        """Convert RGB tuple to RGBColor."""
        return RGBColor(rgb[0], rgb[1], rgb[2])

    def add_title_slide(self, slide_content: SlideContent):
        """Add a title slide."""
        slide = self.prs.slides.add_slide(self._get_slide_layout("title"))

        title_shape = slide.shapes.title
        title_shape.text = slide_content.title
        title_frame = title_shape.text_frame
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(self.text_style.font_size_title)
        title_para.font.color.rgb = self._rgb_to_color(self.text_style.color_title)
        title_para.font.bold = True

        if slide_content.subtitle:
            subtitle_shape = slide.placeholders[1]
            subtitle_shape.text = slide_content.subtitle
            subtitle_frame = subtitle_shape.text_frame
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.font.size = Pt(self.text_style.font_size_subtitle)
            subtitle_para.font.color.rgb = self._rgb_to_color(
                self.text_style.color_subtitle
            )

        if slide_content.footer:
            self._add_footer(slide, slide_content.footer)

    def add_table_slide(self, slide_content: SlideContent):
        """Add a slide with a table."""
        slide = self.prs.slides.add_slide(self._get_slide_layout("table"))

        title_shape = slide.shapes.title
        title_shape.text = slide_content.title

        if slide_content.subtitle:
            title_shape.text += f"\n{slide_content.subtitle}"

        table_content = slide_content.table_content
        if not table_content or not table_content.headers:
            return

        rows = len(table_content.rows) + 1
        cols = len(table_content.headers)

        table_width = (
            self.layout.width - self.layout.margin_left - self.layout.margin_right
        )
        table_height = (
            self.layout.height
            - self.layout.margin_top
            - self.layout.title_height
            - self.layout.margin_bottom
        )

        left = self.layout.margin_left
        top = self.layout.margin_top + self.layout.title_height

        table_shape = slide.shapes.add_table(
            rows, cols, left, top, table_width, table_height
        )
        table = table_shape.table

        for col_idx, header in enumerate(table_content.headers):
            cell = table.cell(0, col_idx)
            cell.text = str(header)
            cell.fill.solid()
            cell.fill.fore_color.rgb = self._rgb_to_color(
                self.table_style.header_bg_color
            )
            para = cell.text_frame.paragraphs[0]
            para.font.bold = True
            para.font.size = Pt(self.text_style.font_size_table)
            para.font.color.rgb = self._rgb_to_color(self.table_style.header_font_color)
            para.alignment = PP_ALIGN.CENTER

        for row_idx, row_data in enumerate(table_content.rows):
            for col_idx, cell_value in enumerate(row_data):
                if col_idx >= cols:
                    break
                cell = table.cell(row_idx + 1, col_idx)
                cell.text = str(cell_value) if cell_value is not None else ""

                if row_idx % 2 == 0:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = self._rgb_to_color(
                        self.table_style.row_bg_color_odd
                    )

                para = cell.text_frame.paragraphs[0]
                para.font.size = Pt(self.text_style.font_size_table)
                para.alignment = PP_ALIGN.CENTER if col_idx == 0 else PP_ALIGN.LEFT

        if slide_content.footer:
            self._add_footer(slide, slide_content.footer)

    def add_figure_slide(self, slide_content: SlideContent):
        """Add a slide with a chart."""
        slide = self.prs.slides.add_slide(self._get_slide_layout("figure"))

        title_shape = slide.shapes.title
        title_shape.text = slide_content.title

        figure_content = slide_content.figure_content
        if not figure_content:
            return

        chart_width = (
            self.layout.width - self.layout.margin_left - self.layout.margin_right
        )
        chart_height = (
            self.layout.height
            - self.layout.margin_top
            - self.layout.title_height
            - self.layout.footer_height
            - self.layout.margin_bottom
        )

        left = self.layout.margin_left
        top = self.layout.margin_top + self.layout.title_height

        try:
            add_chart_to_slide(
                slide,
                figure_content,
                left,
                top,
                chart_width,
                chart_height,
            )
        except Exception as e:
            logger.warning(f"Failed to add chart: {e}")
            placeholder = slide.shapes.add_textbox(left, top, chart_width, chart_height)
            tf = placeholder.text_frame
            tf.text = f"[Chart placeholder: {figure_content.chart_type}]"

        if slide_content.footer:
            self._add_footer(slide, slide_content.footer)

    def add_listing_slide(self, slide_content: SlideContent):
        """Add a slide with a data listing."""
        listing_content = slide_content.listing_content
        if not listing_content:
            return

        listing_slide = SlideContent(
            slide_type="table",
            title=slide_content.title,
            subtitle=slide_content.subtitle,
            footer=slide_content.footer,
            table_content=type(listing_content)(
                headers=listing_content.columns,
                rows=listing_content.data[: listing_content.max_rows],
            ),
        )
        self.add_table_slide(listing_slide)

    def add_text_slide(self, slide_content: SlideContent):
        """Add a slide with text content."""
        slide = self.prs.slides.add_slide(self._get_slide_layout("text"))

        title_shape = slide.shapes.title
        title_shape.text = slide_content.title

        if slide_content.text_content:
            content_width = (
                self.layout.width - self.layout.margin_left - self.layout.margin_right
            )
            content_height = (
                self.layout.height
                - self.layout.margin_top
                - self.layout.title_height
                - self.layout.footer_height
            )

            left = self.layout.margin_left
            top = self.layout.margin_top + self.layout.title_height

            text_box = slide.shapes.add_textbox(
                left, top, content_width, content_height
            )
            tf = text_box.text_frame
            tf.word_wrap = True
            tf.text = slide_content.text_content

            for para in tf.paragraphs:
                para.font.size = Pt(self.text_style.font_size_body)
                para.font.color.rgb = self._rgb_to_color(self.text_style.color_body)

        if slide_content.footer:
            self._add_footer(slide, slide_content.footer)

    def _add_footer(self, slide, text: str):
        """Add footer text to bottom of slide."""
        footer_width = (
            self.layout.width - self.layout.margin_left - self.layout.margin_right
        )
        footer_height = self.layout.footer_height

        left = self.layout.margin_left
        top = self.layout.height - self.layout.margin_bottom - footer_height

        footer_box = slide.shapes.add_textbox(left, top, footer_width, footer_height)
        tf = footer_box.text_frame
        tf.text = text

        para = tf.paragraphs[0]
        para.font.size = Pt(self.text_style.font_size_footer)
        para.font.color.rgb = self._rgb_to_color(self.text_style.color_footer)
        para.alignment = PP_ALIGN.CENTER

    def add_slide(self, slide_content: SlideContent):
        """Add a slide based on its type."""
        slide_type = slide_content.slide_type.lower()

        if slide_type == "title":
            self.add_title_slide(slide_content)
        elif slide_type == "table":
            self.add_table_slide(slide_content)
        elif slide_type == "figure":
            self.add_figure_slide(slide_content)
        elif slide_type == "listing":
            self.add_listing_slide(slide_content)
        elif slide_type == "text":
            self.add_text_slide(slide_content)
        else:
            logger.warning(f"Unknown slide type: {slide_type}, treating as text")
            self.add_text_slide(slide_content)

    def render_slide_deck(self, slide_deck: SlideDeck) -> Presentation:
        """Render complete slide deck to presentation.

        Args:
            slide_deck: SlideDeck with all slides

        Returns:
            Presentation object
        """
        self.create_presentation()

        for slide_content in slide_deck.slides:
            try:
                self.add_slide(slide_content)
            except Exception as e:
                logger.error(f"Failed to add slide '{slide_content.title}': {e}")

        return self.prs

    def save(self, output_path: str) -> str:
        """Save presentation to file.

        Args:
            output_path: Output file path

        Returns:
            Path to saved file
        """
        if not self.prs:
            raise ValueError("No presentation to save. Call render_slide_deck() first.")

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        self.prs.save(str(path))
        logger.info(f"Saved presentation to: {path}")

        return str(path)


def render_output(
    slide_deck: SlideDeck,
    output_path: str = "generated/platinum/report.pptx",
) -> str:
    """Convenience function to render slide deck to PPTX.

    Args:
        slide_deck: SlideDeck with all slides
        output_path: Output file path

    Returns:
        Path to saved file
    """
    renderer = PPTXRenderer()
    renderer.render_slide_deck(slide_deck)
    return renderer.save(output_path)


def render_deliverables(
    deliverables: List[dict],
    study_info: dict,
    output_path: str = "generated/platinum/report.pptx",
    provider: str = "deepseek",
    db_path: Optional[str] = None,
) -> str:
    """Generate and render deliverables to PPTX.

    Args:
        deliverables: List of deliverable dicts from meta.platinum_dictionary
        study_info: Study information dict
        output_path: Output file path
        provider: LLM provider
        db_path: Optional database path for data lookup

    Returns:
        Path to saved file
    """
    from olympus.platinum.agent import PlatinumAgent

    agent = PlatinumAgent(provider=provider, db_path=db_path)

    print(f"Generating slide deck for {len(deliverables)} deliverables...")

    slide_deck = agent.generate_slide_deck(study_info, deliverables)

    print(f"Generated {len(slide_deck.slides)} slides")

    return render_output(slide_deck, output_path)
